### ISSUE TITLE
Setup instructions required

### ISSUE THREAD

**Issue by Mafin-dev** [Mcamilo/AskReddit-video-bot#1]
There is no way anyone can setup this repo. 
Where do I get a "reddit-video-maker-7dbf..." private_key_id? What even is that? 
Why and how can you assume anyone knows anything about snoowrap? I have never heard about that and there are credentials needed also. If you google this Framework(?) you find 3 pages for easy credential access but not a single one is officialy by snoowrap. 
Please provide a easy step by step instruction for setting up this repo. Thanks
@Mcamilo

**Comment by RockyLinuxEnthusiast** [comment]
Please give Setup instruction for Ubuntu Linux

**Comment by Mcamilo** [comment]
Hello @Mafin-dev ! 

Sorry for the over a year-long delay to respond.

I finally created a proper Readme file with step by step instructions for setting up the repo.

I've also got back to maintaining this repo, so hopefully there's going to be new things coming soon.

Cheers!
